[project]
name = "nanobind_uv_workspace_example"
version = "1"
requires-python = ">=3.12"
dependencies = ["pypets[cat,dog]"]

[[tool.uv.index]]
name = "localhost"
url = "http://localhost/simple"
default = true
